"""Add tax_mode and vat_rate to users

Revision ID: 5fc9f30c2893
Revises: aad39be764f5
Create Date: 2026-09-20 23:54:10.301920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fc9f30c2893'
down_revision: Union[str, Sequence[str], None] = 'aad39be764f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('tax_mode', sa.String(length=32), server_default='usn_6', nullable=False))
    op.add_column('users', sa.Column('vat_rate', sa.Numeric(precision=5, scale=2), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'vat_rate')
    op.drop_column('users', 'tax_mode')
    # ### end Alembic commands ###
