"""Initial tables

Revision ID: bcd5eae9239b
Revises: 
Create Date: 2026-09-20 06:47:26.714469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bcd5eae9239b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tariff_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('marketplace', sa.String(length=32), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('marketplace', 'key', name='uq_tariff_marketplace_key')
    )
    op.create_index(op.f('ix_tariff_settings_marketplace'), 'tariff_settings', ['marketplace'], unique=False)
    op.create_table('tax_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('rate_percent', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tax_rates')
    op.drop_index(op.f('ix_tariff_settings_marketplace'), table_name='tariff_settings')
    op.drop_table('tariff_settings')
    # ### end Alembic commands ###
